alamii:
  target: bigquery
  outputs:
    bigquery:
      type: bigquery
      job_execution_timeout_seconds: 300
      job_retries: 1
      method: service-account
      location: asia-southeast2
      project: "alamii"
      dataset: "sales_production"
      keyfile: "{{ env_var('DBT_GOOGLE_BIGQUERY_KEYFILE') }}"
      priority: interactive
      threads: 1
