name: Sales Drive Deduplicator

on:
  workflow_dispatch:
    inputs:
      resumeUrl:
        description: 'The webhook URL to send the final status to.'
        required: false
        type: string

env:
  DBT_PROFILES_DIR: ./
  DBT_GOOGLE_PROJECT: alamii
  DBT_GOOGLE_BIGQUERY_DATASET: sales_production
  DBT_GOOGLE_BIGQUERY_KEYFILE: ./dbt-service-account.json

jobs:
  dbt:
    name: Run Transformation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: pip3 install dbt-bigquery
      - run: dbt --version
      - run: 'echo "$KEYFILE" > ./dbt-service-account.json'
        shell: bash
        env:
          KEYFILE: ${{secrets.DBT_GOOGLE_BIGQUERY_KEYFILE}}
      - run: "dbt run --select v2_sales_drive_final"
  notify:
    name: Notify
    needs: dbt
    runs-on: ubuntu-latest

    if: github.event.inputs.resumeUrl != '' && always()
    steps:
      - name: Send status to webhook
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"status": "${{ needs.main_job.result }}"}' \
          "${{ github.event.inputs.resumeUrl }}"
